export const TodoActionTypes = {
    CREATE_TODO: 'CREATE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    DESTROY_TODO: 'DESTROY_TODO',
    TOGGLE_TODO_COMPLETED: 'TOGGLE_TODO_COMPLETED',
    TOGGLE_ALL_TODO_COMPLETED: 'TOGGLE_ALL_TODO_COMPLETED',
    CLEAR_ALL_COMPLETED_TODO: 'CLEAR_ALL_COMPLETED_TODO',
    SET_SELECTED_FILTER_LABEL: 'SET_SELECTED_FILTER_LABEL'
};